env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './tsconfig.lint.json'

plugins:
  - jest
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
