name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

inputs:
  github_token:
    description: 'a github access token'
    required: true
    default: ${{ github.token }}
  pr_url:
    description:
      'the target pr url. This is used for taking pr number in workflows
      triggered by "issue_comment" event'
    required: true
    default: ${{ github.event.issue.pull_request.url }}
  threshold:
    description:
      'a threshold at which a message is sent when the number of comments
      exceeds this'
    required: true
    default: 25

runs:
  using: node20
  main: dist/index.js
