name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github_token:
    description: 'a github access token'
    required: true
    default: ${{ github.token }}
  pr_number:
    description:
      'a target pr number. This is set for events triggered by issue_comment'
    required: false
  threshold:
    description:
      'a threshold at which a message is sent when the number of comments
      exceeds this'
    required: true
    default: 25

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
