name: 'recommend-mobpro-action'
description: 'recommend to do mob programming when a discussion drags on'
author: 'Tomoya KASHIFUKU<tnyo43@gmail.com>'

inputs:
  github_token:
    description: 'a github access token'
    required: true
    default: ${{ github.token }}
  threshold:
    description:
      'a threshold at which a message is sent when the number of comments
      exceeds this'
    required: true
    default: 25
  debug:
    description: show debug message (for development)
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      if: github.event_name != 'issue_comment' || github.event.issue.pull_request
    - run: 'node ${GITHUB_ACTION_PATH}/dist/index.js'
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
        INPUT_DEBUG: ${{ inputs.debug }}
      if: github.event_name != 'issue_comment' || github.event.issue.pull_request
