name: 'recommend-mobpro-action'
description: 'recommend to do mob programming when a discussion drags on'
author: 'Tomoya KASHIFUKU<tnyo43@gmail.com>'

inputs:
  github_token:
    description: 'a github access token'
    required: true
    default: ${{ github.token }}
  threshold:
    description:
      'a threshold at which a message is sent when the number of comments
      exceeds this'
    required: true
    default: 25

runs:
  using: node20
  main: dist/index.js
